/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppMain: typeof import('./src/components/AppMain.vue')['default']
    ChartContainer: typeof import('./src/components/chart/ChartContainer.vue')['default']
    ChartHeader: typeof import('./src/components/chart/ChartHeader.vue')['default']
    ChartSettings: typeof import('./src/components/chart/ChartSettings.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    InputFieldsRow: typeof import('./src/components/InputFieldsRow.vue')['default']
  }
}
